@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 前端界面
participant 后端
activate 用户
activate 前端界面

用户 -> 前端界面: 按内容检索
activate 后端
前端界面 -> 后端: 发送查询请求
后端 --> 前端界面: 相关法条
前端界面 --> 用户: 相关法条
deactivate 后端

用户 -> 前端界面: 筛选搜索结果
前端界面 --> 用户: 筛选后的结果

用户 -> 前端界面: 按标题检索
activate 后端
前端界面 -> 后端: 发送查询请求
后端 --> 前端界面: 相关法律
前端界面 --> 用户: 相关法律
deactivate 后端

用户 -> 前端界面: 查看法律详情
activate 后端
前端界面 -> 后端: 发送查询请求
后端 --> 前端界面: 法律中包含的所有条款项目
前端界面 --> 用户: 法律中包含的所有条款项目
deactivate 后端

用户 -> 前端界面: 添加法律正文
activate 后端
前端界面 -> 后端: 发送添加请求
前端界面 --> 用户: 在文档中插入法律正文
deactivate 后端

用户 -> 前端界面: 查看文档引用的法律
activate 后端
前端界面 -> 后端: 发送查询请求
后端 --> 前端界面: 文档引用的法律
前端界面 --> 用户: 文档引用的法律
deactivate 后端

@enduml