@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor 用户
participant 前端界面
participant 后端
activate 用户
activate 前端界面
loop 用户输入内容
    用户 -> 前端界面: 输入搜索条件、搜索内容
end
activate 后端
前端界面 -> 后端: 发送查询请求
后端 --> 前端界面: 分页的法律列表
前端界面 --> 用户: 分页的法律列表
deactivate 后端
用户 -> 前端界面: 对某一项展开内容
前端界面 -> 前端界面: 显示简略的正文或相关法条
用户 -> 前端界面: 查看某一项详情
前端界面 -> 前端界面: 跳转至法律详情页面


用户 -> 前端界面: 进入法律详情页面
activate 后端
前端界面 -> 后端: 检索一条法律的全部信息
后端 --> 前端界面: 法律基本信息和正文各部分
前端界面 -> 后端: 检索一条法律的相关法律
后端 --> 前端界面: 相关法律列表
前端界面 --> 用户: 展示结果
deactivate 后端
用户 -> 前端界面: 展开/收起一个项目的折叠列表
前端界面 --> 用户: 展开/收起该项目列表
@enduml